### ISSUE TITLE
suggestion: change some of the moons into an uninhabitable moon?

### ISSUE THREAD

**Issue by Seamonster778778778788** [Pairjax/SQBeyondPublic#142]
hear me out

make people wear their spacesuits while on it/be indoors

because most satellites like that irl dont really have atmospheres like that

**Comment by MrBarramundi** [comment]
There are only two moons (unless more are planning on being added then in that case I like the idea) and one of them is already like that. Is this suggestion closed then? Tell me if I'm wrong.

**Comment by fin444** [comment]
Cueneva is already like this
