### ISSUE TITLE
Items despawn on chunks that should not be loaded

### ISSUE THREAD

**Issue by Creepopolous** [Pairjax/SQBeyondPublic#354]
For many of my recent deaths, I had gotten back to my place of death, with no items present, but the XP, with the same despawn timer, remains despite this. It is unlikely that I had died near the world spawn each time, as it has occurred on every planet I have visited since the first incident.

**Comment by fin444** [comment]
Anecdotally, I can state that this bug has been solved. Or, at least is unreproduceable.
