### ISSUE TITLE
Suggestion for the Farming Supplies when redeeming votes

### ISSUE THREAD

**Issue by MrBarramundi** [Pairjax/SQBeyondPublic#482]
So as far as I can tell, Kelp doesn't exist in the great universe of StarQuest. I've gone to the two planets that are listed as can grow Kelp but none could be found. I have also been to other planets with oceans but have had no luck. Since 1-31-20 I've also been asking people that are online if they have any kelp and none have said yes to owning any. I've had people tell me they've seen it but can't remember where or they point me to Jurion. All the markets are sold out as well and I've been checking each one everyday. I ask that Kelp be added so this, as to my knowledge, extinct species of plant & source of food can once again grace existence. Currently the Farming supplies are filled with a variety of growables but none of which are the main advertised crop that can grow on the two kelp crop planets. I'm just saying it doesn't feel inclusive to us Avaquoians and Qillions. Thank you, Mr. B

**Comment by fin444** [comment]
There is now kelp
