### ISSUE TITLE
Zombie pigman dont spawn on tyder (when they should)

### ISSUE THREAD

**Issue by Seamonster778778778788** [Pairjax/SQBeyondPublic#502]
they spawn maybe once a year, conditions for spawning them might be the same as the nether itself

**Comment by fin444** [comment]
They also don't spawn on Xira, when the wiki says they should

**Comment by Seamonster778778778788** [comment]
this is in the process of being fixed

**Comment by fin444** [comment]
SQMobs has been fixed and updated, please make a new bug report if this happens again.
