### ISSUE TITLE
sometimes when you travel thru a slipgate/slipspace, your ship ditches you

### ISSUE THREAD

**Issue by icekoob** [Pairjax/SQBeyondPublic#511]
happened today around 3:31 pm cst with mr. primal_stage, he was travelling through the regalis-ashlan gate and his ship ditched him

**Comment by icekoob** [comment]
![2020-04-20_15 36 06](https://user-images.githubusercontent.com/12261784/79797665-47cb0880-831d-11ea-8867-13691c1088a6.png)
![2020-04-20_15 34 29](https://user-images.githubusercontent.com/12261784/79797667-48fc3580-831d-11ea-9f3c-413f66f2c5d3.png)

**Comment by Seamonster778778778788** [comment]
doesnt happen often

**Comment by fin444** [comment]
Any other cases of this occuring?
