### ISSUE TITLE
Redstone Repeaters

### ISSUE THREAD

**Issue by JustAKoala12** [Pairjax/SQBeyondPublic#542]
Certain repeaters wont light up when they are supposed to
![2020-05-06_20 02 17](https://user-images.githubusercontent.com/64880915/81246387-adcdb600-8fd4-11ea-9d31-8d0674502bc3.png)

**Comment by Seamonster778778778788** [comment]
break the repeater/redstone and replace it @JustAKoala12

**Comment by fin444** [comment]
This is just a Minecraft redstone bug, nothing specific to SQ
