### ISSUE TITLE
Sudden "Ship has been removed or destroyed!"

### ISSUE THREAD

**Issue by SirLoser** [Pairjax/SQBeyondPublic#544]
**Describe the bug**
Upon entering Erilon, my capital ship declared "The ship has been removed or destroyed!" Interaction with ship sign says "Ship detected!" "Ship piloted!" "The ship has been removed or destroyed!" Attempts to move sign or replace block sign was own have proven futile. [Correction, upon moving the sign in an effort to produce screenshots, suddenly it worked. Still cannot put sign in original position.] [Addition, being able to leave Erilon thanks to the moved sign, the ship sign was able to be returned to its original position in space.] [Addition, happened again upon entering Sabaka.]

**To Reproduce**
1. Place Capital Ship sign
2. Interact with sign
3. See error

**Expected behavior**
Expected ship to redetect properly and pilot as a capital ship

**Screenshots**
![2020-05-08_02 32 31](https://user-images.githubusercontent.com/21044059/81382914-c4f3cd00-90d4-11ea-9f3b-ffea613466bc.png)
![2020-05-08_02 32 35](https://user-images.githubusercontent.com/21044059/81382923-c91fea80-90d4-11ea-82f8-4872c4d7aeab.png)
![2020-05-08_02 35 37](https://user-images.githubusercontent.com/21044059/81382934-d046f880-90d4-11ea-96e1-b19046d2babe.png)

![2020-05-08_02 35 39](https://user-images.githubusercontent.com/21044059/81382944-d3da7f80-90d4-11ea-8b43-ca31864a6e93.png)

![2020-05-08_02 35 55](https://user-images.githubusercontent.com/21044059/81382953-d8069d00-90d4-11ea-9ead-b9a3f19ecd61.png)

**Additional context**
There is a capital ship stuck in the slipspace holding place. It prevented me from entering slipspace when I slipped to an area just outside Erilon, although the travel percentage counter continued and I was eventually teleported to my destination. Uncertain if this has any effect on the current problem. I was headed to Erilon to deliver wool to a customer. Immediately upon entering Erilon, the bug occurred.

**Comment by Jarkyc** [comment]
Looking into now. Possible source identified.

**Comment by Jarkyc** [comment]
Should be fixed. Please post another issue if this problem persists.

**Comment by Seamonster778778778788** [comment]
reopen this issue*
