### ISSUE TITLE
Slipspace Currently Blocked

### ISSUE THREAD

**Issue by KneelHate** [Pairjax/SQBeyondPublic#546]
Currently attempting to use slipspace provides an initial error message along the lines of "block at x,y,z is preventing the grid from moving."

Jumps and slipgates still seems to work, getting the player and ship from one place to another. But it seems the player sits at point A for the full time of the jump, potentially leaving them vulnerable to attacks that they would normally not be.

The issue prevents blink drives from working as well.

**Comment by Laserlance141** [comment]
just world-edited out the blockage, should be fixed
