### ISSUE TITLE
Forge NPC Gone

### ISSUE THREAD

**Issue by fin444** [Pairjax/SQBeyondPublic#547]
**Describe the bug**
The Forge NPC is not there

**To Reproduce**
1. Go to the Forge

**Expected behavior**
I expected there to be an NPC

**Screenshots**
[here](https://i.imgur.com/Pdj4159.jpg)

**Comment by Laserlance141** [comment]
I checked this when the forge spawned at 12 server time, and the forgemaster was there
will check one more time before closing

**Comment by fin444** [comment]
May have been a one-time bug, no way to tell what caused it.

**Comment by fin444** [comment]
After another check, this appears to be a one-time or very rare bug. With not enough information to go on, and the bug not really occurring, it doesn't really matter.

**Comment by Laserlance141** [comment]
This happened again at 6:02 on 5/12/20 at coords 21540 100 20453 in a static storm
![2020-05-12_18 02 13](https://user-images.githubusercontent.com/13091148/81759989-0ab8e880-947b-11ea-91d0-2c8ee9059e3c.png)
