### ISSUE TITLE
Earning double credits/reputation when wolf kills a mob

### ISSUE THREAD

**Issue by Kappsune** [Pairjax/SQBeyondPublic#548]
**Describe the bug**
Whenever my tamed wolf on Tyder kills a skeleton, I receive the message for credits and Vapid reputation earned twice. It is usually a lesser amount the second time, so I would assume this means it is counting it as two mobs killed separately. This is happening whether I contribute to the damage to the skeleton or the wolf kills it all by itself.

**To Reproduce**
Tame a wolf
Let it kill a hostile mob

**Expected behavior**
I should only see the message and earn the rewards one time.

**Screenshots**
![2020-05-09_14 47 59](https://user-images.githubusercontent.com/63769224/81482441-01264b00-9205-11ea-909f-5290e83d255e.png)

**Comment by Laserlance141** [comment]
related to #405

**Comment by fin444** [comment]
Fixed a while ago, forgot to close
