### ISSUE TITLE
spaces in chat

### ISSUE THREAD

**Issue by Seamonster778778778788** [Pairjax/SQBeyondPublic#549]
**Describe the suggestion**
A clear and concise description of what the suggestion is.
add spaces between rank's in game and the name and the rank
**Why will this make StarQuest better?**
Explain why you think this feature will be beneficial to players' gameplay experience.
easier to read :)
**Additional info**
Add anything else you want to say about your suggestion here.
could also replace the > with something else
![image](https://user-images.githubusercontent.com/34897864/81488045-84599800-9229-11ea-8331-0ad1bae0deff.png)

**Comment by fin444** [comment]
So would you want something like this?
`[G] [Buccaneer II] [Admin] Sea (something other than >)`

**Comment by Seamonster778778778788** [comment]
yes maam, jarkyc said he wants to rewrite the chat though

**Comment by Seamonster778778778788** [comment]
the spaces is just an idea, idk if it would look good in practice

**Comment by fin444** [comment]
[How does this look?](https://i.imgur.com/O7RC6HZ.jpg)

**Comment by Seamonster778778778788** [comment]
@Jarkyc @Pairjax thoughts?

**Comment by fin444** [comment]
This is being applied during the next server restart
