### ISSUE TITLE
Ship detection math wrong

### ISSUE THREAD

**Issue by HailOVERLORD** [Pairjax/SQBeyondPublic#551]
The math to calculate the armor/wool percentages is not working right. 

To reproduce the issue, use irl math to create a starfighter with the absolute max armor and min wool. It will not work unless you add way too much extra wool.

**Comment by fin444** [comment]
Attempted to reproduce using the following ship specs:
30 total blocks
12 wool (40%)
6 armor (20%)
12 misc. blocks (40%)

The ship detected as expected, and showed correct numbers in `/ship info`.
