### ISSUE TITLE
when poeple get kicked while afk, when they rejoin some time later it says they were kicked again

### ISSUE THREAD

**Issue by Seamonster778778778788** [Pairjax/SQBeyondPublic#552]
**Describe the bug**
title
**To Reproduce**
1. get afk kicked
2. rejoin

**Expected behavior**
not
**Screenshots**
![image](https://user-images.githubusercontent.com/34897864/81522800-6bc4ad00-9311-11ea-8312-b5975571242c.png)

**Additional context**

**Comment by fin444** [comment]
I think there might be more of a bug at play here, I can't remember ever being kicked for AFK

**Comment by Seamonster778778778788** [comment]
probably would be the last time you joined @fin444
