### ISSUE TITLE
salvage does not work properly

### ISSUE THREAD

**Issue by Seamonster778778778788** [Pairjax/SQBeyondPublic#553]
Issue: I salvaged an iron chestplate that had full durability and got nothing from it, despite it saying I got 2 iron ingots back.

How did it happen: I used the MCMMO salvage by right clicking the chestplate on a gold block

theory: salvage broke

**Comment by Seamonster778778778788** [comment]
![image](https://user-images.githubusercontent.com/34897864/81624293-6ae85580-93bb-11ea-90ea-7838c5cce5fd.png)
no iron in my inventory see bottom

**Comment by fin444** [comment]
This is an McMMO bug, not our fault
