### ISSUE TITLE
Town keeps unclaiming itself

### ISSUE THREAD

**Issue by BoyWonderFTW** [Pairjax/SQBeyondPublic#556]
**Describe the bug**
Upon splitting off from AMT, I started a new HQ for a new town on Feldost, but every restart a part of the town unclaims. I posted a screenshot in mod chat for staff to inspect, and I have no idea whats causing it. This is the second time it has happened, but nothing should be disallowing the hq claim.

**To Reproduce**
1. Claim some part of the town.
2. Watch Dynmap after restart

**Comment by fin444** [comment]
Just a note, dynmap is inconclusive for testing this as it does not always show claims properly, even when they are claimed. #531
