### ISSUE TITLE
Ghast Spawning

### ISSUE THREAD

**Issue by fin444** [Pairjax/SQBeyondPublic#557]
**Describe the bug**
Ghasts have no checks to ensure their spawns are legitimate, and they have very high spawn rates. They often spawn inside of blocks or small spaces when they shouldn't. In fact, they spawn much more frequently than blazes, when it should be the other way around.

**To Reproduce**
1. Go to Xira at night time
2. Turn on hostile mob noises
3. Get tinnitus

**Expected behavior**
Ghasts should not spawn so much.

**Screenshots**
I was too busy fighting for my life against a massive onslaught of fireballs.

**Comment by Jarkyc** [comment]
@Pairjax thought you fixed this
