### ISSUE TITLE
Spawning in space when logging from holo

### ISSUE THREAD

**Issue by HailOVERLORD** [Pairjax/SQBeyondPublic#570]
Twice today, I spawned in space with no gear. The first time I died, and Sea had to refund my inventory because he couldn't see what I had. The second time was right after the 11:05 central server restart and I was able to do /kit spacesuit in time to live...barely. Both times happened when I logged out from holo. The glitch only happens sometimes...perhaps after a server restart? Server restart after logging in holo is my best guess.

TO re-create:
1. Log out in holodeck
2. restart server?       *maybe?
3. Log back in

The glitch only happened 2 out of the 4 times that I logged in holo, which is why I suspect the server restart playing a role, because it had restarted since I logged both times.

 Submitting this the morning after because internet issues

**Comment by APnaptime** [comment]
So far it seems to be a issue mainly associated with you. In my testing and I hope other's experience, this isn't an issue. Does entering and exiting the holodeck normally work for you; Is there any more information that you can provide? Specifically any edge case possibilities. Did you first enter the holodeck at a weird time? Or are you logging out a few minutes before the restart?

Currently, I suspect it is an issue with how combat dummies are handled with holodeck so any information along that line would be a help.

**Comment by HailOVERLORD** [comment]
> So far it seems to be a issue mainly associated with you. In my testing and I hope other's experience, this isn't an issue. Does entering and exiting the holodeck normally work for you; Is there any more information that you can provide? Specifically any edge case possibilities. Did you first enter the holodeck at a weird time? Or are you logging out a few minutes before the restart?
> 
> Currently, I suspect it is an issue with how combat dummies are handled with holodeck so any information along that line would be a help.

It has happened to me twice. The both times I was in holo and logged off when the server restarted. I would try to test it again myself, but I don't want to keep loosing my stuff. I did mention that the glitch is not consistent and only happens some of the time.

**Comment by APnaptime** [comment]
Right before restarts? or a few minutes?

**Comment by HailOVERLORD** [comment]
> Right before restarts? or a few minutes?

One was right before a restart (moments), the other was the night of a restart, meaning I logged off well before the restart, and it restarted while I was logged off in holo.
