### ISSUE TITLE
decayable leaves not decaying

### ISSUE THREAD

**Issue by ConsueTerra** [Pairjax/SQBeyondPublic#585]
**Describe the bug**
I know that some of the trees on the server have leaves that dont decay (persisent=true) from custom trees but trees that are grown from saplings should be decayable (persistent=false) yet they dont decay

**Comment by APnaptime** [comment]
It might have something to do with lag reduction

**Comment by ConsueTerra** [comment]
from what I understand, the decay of leaves is controlled by the random tick of a chunk, which happens anyway, so having leaves decay should not affect performance. The only thing that could cause lag is if leaf decay was causing a considerable number of block updates, however the source of decaybale leaves in any given area is small (because they would only come from sapling grown trees) so the number of block updates and therefore lag is negligible.
