### ISSUE TITLE
Ketch class counting slipdrives and torpedoes as inventory

### ISSUE THREAD

**Issue by ConsueTerra** [Pairjax/SQBeyondPublic#587]
**Describe the bug**
Slipdrive hoppers and dispensers from torpedoes count as inventory

**To Reproduce**
Build a ketch with 2 slip drives, a cargobay, and a torpedo, ship detection fails

**Expected behavior**
If im correct the expected dropper count should be 0 or 1 not 5

**Comment by ConsueTerra** [comment]
Update on this bug, it does indeed seem like slip drives with oak signs do not count as inventory but with any other sign they do, same thing with droppers

**Comment by fin444** [comment]
Duplicate of #476
